apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sjobs-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: k8sjobs
          image: dev4522v/k8sjobs:latest
          command: ["/k8sjobs", "-server=R"]
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8sjobs-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  externalIPs:
    - 80.11.12.10
